### ISSUE TITLE
Widgets not working inside child component

### ISSUE THREAD

**Issue by bart** [juijs/vue-graph#7]
Hey hey, I really like your library, but unfortunately widgets are not working for me. I'm using the ES6 way like this:

```
import Vue from 'vue';
import VueGraph from 'vue-graph';
Vue.use(VueGraph);
```

My HTML looks like this:

```
<graph-pie
    :width="700"
    :height="400"
    :values="chartData.values"
    :names="chartData.names"
    :show-text-type="'outside'"
    :data-format="chartDataValueFormat">
    <legends :names="chartData.names"></legends>
</graph-pie>
```

The legends widget is simply not displayed and also not available in the rendered SVG. Do you have any idea? I'm using the latest version 0.4.1. Thanks!

**Comment by seogi1004** [comment]
I tested it with the sample below and it is OK. T.T.
https://github.com/juijs/vue-graph/blob/master/examples/pie.html

Show me the full source code and I'll check it out!

**Comment by bart** [comment]
Well, when I try the above example it works. Maybe the problem is that I try to use it inside a component. Does this make any difference?

**Comment by seogi1004** [comment]
import Vue from 'vue'
import VueGraph from 'vue-graph'

Vue.use(VueGraph)

var vm = new Vue({
    el: "#app",
    data: {
        values: [ 10, 5, 5, 5 ],
        names: [ 'Apple', 'Google', 'MS', 'Facebook' ]
    },
    methods: {
        dataFormat: function(a, b) {
            if(b) return b + "%";
            return a;
        }
    }
});

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div id="app">
    <graph-pie
            :width="500"
            :height="500"
            :values="values"
            :names="names"
            :active-index="[ 0, 2 ]"
            :active-event="'click'"
            :show-text-type="'inside'"
            :data-format="dataFormat">
        <note :text="'Pie Chart'"></note>
        <legends :names="names"></legends>
        <tooltip :names="names"></tooltip>
    </graph-pie>
</div>
<script src="../dist/build.js"></script>
</body>
</html>

**Comment by seogi1004** [comment]
Could you please show me if there was a script error?

**Comment by bart** [comment]
There was no script error. It just didn't render the widgets. I'm currently trying to reproduce it in a single small project just for testing purposes.

**Comment by seogi1004** [comment]
Try to make the chart size the same as the sample, and increase the padding-bottom value.

**Comment by bart** [comment]
I checked the generated SVG already. It's simply not rendered there :(

**Comment by seogi1004** [comment]
@bart Do other widgets look good?

**Comment by bart** [comment]
None of the widgets works. That's the problem. I don't understand the reason.

**Comment by seogi1004** [comment]
Sorry, but please send it to me with full source code zip file.

**Comment by bart** [comment]
I'm currently working on it. The problem is that I can't send you the entire project :D Trying to isolate the graph part and hopefully finding the issue while doing it.

**Comment by seogi1004** [comment]
So, just send me the javascript part.
The only thing you attach is the markup and the first part of JavaScript.

**Comment by bart** [comment]
All right, just an additional information! It looks like the reason for it is the width and the height I used. Problem is: When using :show-text-type="'outside'" width must be greater than height. Otherwise some labels are missing. But it looks like that this setting destroys plugins / puts them outside of the view.

**Comment by seogi1004** [comment]
@bart The outside option of the pie chart should make padding wide. Please refer to the sample below.
https://codepen.io/seogi1004/pen/oMBgNg

**Comment by bart** [comment]
Yeah, that makes sense, thanks @seogi1004 But the problem still exists. For me it looks like the problem is that widgets are part of the core graph. I even can't see the LegendWidget component in vue dev tools. Could it be a setting in my webpack that this kind of inheritance gets ignored?

**Comment by seogi1004** [comment]
It will not be a web pack issue.
I'd rather have a script error, which is a very difficult problem.

**Comment by bart** [comment]
Hmm, I have no solution currently. Exported the entire graph and using dummy data like this:

```
<template>
    <div>
        <graph-pie
                :width="500"
                :height="500"
                :padding-top="75"
                :padding-right="75"
                :padding-bottom="75"
                :padding-left="75"
                :values="values"
                :names="names"
                :show-text-type="'outside'"
                :shape="'donut'"
                :show-total-value="true">
            <legends :names="names"></legends>
            <tooltip :names="names"></tooltip>
        </graph-pie>
    </div>
</template>

<script>
    import Vue from 'vue';
    import VueGraph from 'vue-graph';

    Vue.use(VueGraph);

    export default {
        data() {
            return {
                values: [ 10, 5, 5, 5 ],
                names: [ 'Apple', 'Google', 'MS', 'Facebook' ],
            };
        },
    };
</script>
```

Result:

<img width="585" alt="screenshot 2018-10-10 at 15 51 19" src="https://user-images.githubusercontent.com/5200235/46740990-5fdfb780-cca4-11e8-9a70-7432d2e33faa.png">

As you can see, none of the widgets works :( Super weird!

**Comment by seogi1004** [comment]
It is a component, not a vue instance.
I know. I will check and comment.

**Comment by bart** [comment]
All right, thank you very much @seogi1004 I really looking forward your response 👍

**Comment by seogi1004** [comment]
I tested it with a component, and I can see the widget well. Once Korea is at dawn, I have to sleep. Let's check again tomorrow.

**Comment by bart** [comment]
Hehe, sleep well @seogi1004 Looking forward a solution tomorrow. Have a good night

**Comment by bart** [comment]
I also reproduced it in an independent project. Worked well there, so it must be something with the current project configuration. Because it doesn't seem to be package related, I will finally close this issue. Sorry for wasting your time! If I find the reason I'll let you know here. Maybe in the future someone else will come up with a similar issue.

**Comment by bart** [comment]
All right, I finally fixed it. The reason is still super weird. We are using Vue router and the master page used typescript with vue-property-decorator package. I replaced the syntax in this file to normal JS. Et voila, it works now. A mixture of TS and JS doesn't seem to be a good idea!
