### ISSUE TITLE
Legends Widget is not reactive

### ISSUE THREAD

**Issue by bart** [juijs/vue-graph#8]
It looks like the legends widget is not checking for changes of its names property. Here is an example:

```
<template>
    <section class="container">
        Select your dataset:

        <select v-model="dataset">
            <option value="set1">Set 1</option>
            <option value="set2">Set 2</option>
        </select>

        <graph-pie
                :width="600"
                :height="350"
                :padding-bottom="100"
                :values="data[dataset].values"
                :names="data[dataset].names">
            <legends :names="data[dataset].names"></legends>
        </graph-pie>
    </section>
</template>

<script>
    export default {
        data() {
            return {
                dataset: 'set1',
                data: {
                    set1: {
                        values: [ 10, 5, 5, 5 ],
                        names: [ 'Apple', 'Google', 'MS', 'Facebook' ],
                    },

                    set2: {
                        values: [ 7, 10, 12, 3 ],
                        names: [ 'Lufthansa', 'Southwest', 'Iberia', 'Virgin' ],
                    }
                },
            }
        }
    }
</script>

<style>
    .container {
        min-height: 100vh;
        display: flex;
        justify-content: center;
        align-items: center;
        text-align: center;
    }
</style>
```

When I switch between set 1 and set 2 values are changing but the legend doesn't. Do you have an idea how I can solve this issue?

Thanks a lot!

**Comment by seogi1004** [comment]
The names property is not a watch target.
If necessary, you can implement watch.

**Comment by bart** [comment]
Oh that would be amazing, because I need this feature. When I select a different set it must change the legends as well. You must do it in the package, right? Or is it possible to watch these changes from outside and update labels this way? Thanks a lot!

**Comment by seogi1004** [comment]
@bart Added the ability to monitor the 'names' property in the 'tooltip' and 'legends' widgets in version v0.4.2

**Comment by bart** [comment]
Wow, that's awesome. Thank you so much @seogi1004 for the very quick solution and release 0.4.2!

**Comment by bart** [comment]
I tested it in the actual project and it works well now! Thanks a lot for your effort @seogi1004

**Comment by seogi1004** [comment]
@bart You're welcome. I just added very simple code.
Please use it a lot in the future. Thank you.

'''
watch: {
        names: function(newVal, oldVal) {
            this.names = newVal;
            this.$parent.chart.render(true);
        }
    },
'''

**Comment by bart** [comment]
You mean I could also use this from outside without needing an update of the package, right? Thanks for sharing but in version 0.4.2 it's already implemented so I'll use it :)

**Comment by seogi1004** [comment]
Ah T.T just showed the changed code.
