### ISSUE TITLE
Vue Graph IE 11 - babel-polyfill not working

### ISSUE THREAD

**Issue by shalachev** [juijs/vue-graph#9]
Tried to import babel-polyfill but it seems that It doesn't go through vue-graph js, therefore, the entire application breaks on IE 11.

Is there a way to make this work on IE 11?

**Comment by seogi1004** [comment]
I'll check!

**Comment by seogi1004** [comment]
I think I can solve the problem in the following way.
https://stackoverflow.com/questions/44529912/babel-polyfill-array-from-for-ie11-support

**Comment by dbsimeonov** [comment]
Same issue here.
After some research saw that you can import it with 3 different ways like required/import/and cdn. None of which worked for me.

**Comment by seogi1004** [comment]
@shalachev How do you use 'vue-graph'? Are you importing and using component by component? Or do you load it as a plugin?

**Comment by seogi1004** [comment]
@shalachev If you use the bundle file, you need to add the "dist/babel-polyfill.js" file to the first of the HTML headers.

https://babeljs.io/docs/en/babel-polyfill

**Comment by shalachev** [comment]
@seogi1004  - I've cloned the project then compiled it through polyfill and works fine now.
